-- ============================================================
--  MS TRAVELS — SEAT INTEGRITY & REFUND HARDENING (additive)
--  Run AFTER supabase-schema.sql, in: Supabase Dashboard → SQL Editor.
--
--  Fixes three audit-blocking defects without restructuring data:
--   1. Double-sell race  -> BEFORE INSERT trigger rejects an already-taken seat
--   2. Open `with check (true)` insert -> a constrained insert policy + the trigger
--      (the production-grade fix is to move inserts behind an Edge Function with the
--       service role and rate-limiting; this is the SQL-only hardening in the meantime)
--   3. Seat holds -> a seat_holds table + RPCs so a selection reserves seats for 8 min,
--      and booked_seats reflects live holds (no more "seat taken" only at Pay Now)
--   4. Client-computed refunds -> a SECURITY DEFINER cancel_booking() that recomputes
--      the tier from the SERVER clock and the stored fare (client value never trusted)
-- ============================================================

-- ------------------------------------------------------------
-- 1. SEAT HOLDS
-- ------------------------------------------------------------
create table if not exists public.seat_holds (
  id            bigint generated by default as identity primary key,
  route_id      bigint not null references public.bus_routes(id),
  journey_date  date   not null,
  seat_id       text   not null,
  hold_token    text   not null,            -- random token the browser keeps for the session
  expires_at    timestamptz not null,
  created_at    timestamptz not null default now()
);

-- One live hold per seat per route+date. Expired rows are ignored by booked_seats
-- and cleaned up opportunistically; this unique index blocks two concurrent holds.
create unique index if not exists uniq_active_hold
  on public.seat_holds (route_id, journey_date, seat_id);

alter table public.seat_holds enable row level security;

-- Holds carry no PII; allow the public flow to manage them via the RPCs below.
drop policy if exists "holds_all" on public.seat_holds;
create policy "holds_all" on public.seat_holds for all to anon, authenticated
  using (true) with check (true);

-- ------------------------------------------------------------
-- 2. booked_seats — now CONFIRMED bookings UNION live (non-expired) holds
--    (replaces the function from supabase-schema.sql)
-- ------------------------------------------------------------
create or replace function public.booked_seats(p_route_id bigint, p_journey_date date)
returns jsonb
language sql
stable
security definer
set search_path = public
as $$
  with confirmed as (
    select elem as seat
    from public.bus_bookings b
    cross join lateral jsonb_array_elements(b.seats) as elem
    where b.route_id = p_route_id
      and b.journey_date = p_journey_date
      and b.status = 'CONFIRMED'
  ),
  held as (
    select to_jsonb(seat_id) as seat
    from public.seat_holds
    where route_id = p_route_id
      and journey_date = p_journey_date
      and expires_at > now()
  )
  select coalesce(jsonb_agg(distinct seat), '[]'::jsonb)
  from (select seat from confirmed union all select seat from held) s;
$$;

grant execute on function public.booked_seats(bigint, date) to anon, authenticated;

-- ------------------------------------------------------------
-- 3. HOLD / RELEASE RPCs
--    hold_seats: clears the caller's prior holds, drops expired rows, then tries
--    to reserve the requested seats. Returns the seats it could NOT get (taken).
-- ------------------------------------------------------------
create or replace function public.hold_seats(
  p_route_id bigint, p_journey_date date, p_seats jsonb, p_token text, p_minutes int default 8
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  s text;
  conflicts jsonb := '[]'::jsonb;
begin
  delete from public.seat_holds where expires_at <= now();
  delete from public.seat_holds where hold_token = p_token;          -- replace this session's holds

  for s in select jsonb_array_elements_text(p_seats) loop
    -- already confirmed?
    if exists (
      select 1 from public.bus_bookings b
      where b.route_id = p_route_id and b.journey_date = p_journey_date
        and b.status = 'CONFIRMED' and b.seats ? s
    ) then
      conflicts := conflicts || to_jsonb(s);
      continue;
    end if;
    begin
      insert into public.seat_holds (route_id, journey_date, seat_id, hold_token, expires_at)
      values (p_route_id, p_journey_date, s, p_token, now() + make_interval(mins => p_minutes));
    exception when unique_violation then
      conflicts := conflicts || to_jsonb(s);                          -- held by someone else
    end;
  end loop;

  return jsonb_build_object('conflicts', conflicts);
end;
$$;

grant execute on function public.hold_seats(bigint, date, jsonb, text, int) to anon, authenticated;

create or replace function public.release_seats(p_token text)
returns void
language sql
security definer
set search_path = public
as $$ delete from public.seat_holds where hold_token = p_token; $$;

grant execute on function public.release_seats(text) to anon, authenticated;

-- ------------------------------------------------------------
-- 4. PREVENT DOUBLE-SELL AT INSERT (database-level safety net)
--    Rejects a booking if any of its seats are already CONFIRMED for the same
--    route+date, and clears any holds it consumes. This holds even if two requests
--    race past the application-level re-check.
-- ------------------------------------------------------------
create or replace function public.prevent_double_booking()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  taken text[];
begin
  select array_agg(elem)
  into taken
  from jsonb_array_elements_text(new.seats) elem
  where exists (
    select 1 from public.bus_bookings b
    where b.route_id = new.route_id
      and b.journey_date = new.journey_date
      and b.status = 'CONFIRMED'
      and b.seats ? elem
  );

  if taken is not null then
    raise exception 'Seat(s) % already booked for this trip', array_to_string(taken, ', ')
      using errcode = '23505';
  end if;

  -- consume holds for these seats so they free up immediately
  delete from public.seat_holds
  where route_id = new.route_id and journey_date = new.journey_date
    and seat_id in (select jsonb_array_elements_text(new.seats));

  return new;
end;
$$;

drop trigger if exists trg_prevent_double_booking on public.bus_bookings;
create trigger trg_prevent_double_booking
  before insert on public.bus_bookings
  for each row execute function public.prevent_double_booking();

-- ------------------------------------------------------------
-- 5. CONSTRAIN THE ANONYMOUS INSERT POLICY
--    Still allows guest checkout, but the public anon key can no longer write
--    arbitrary rows: status must be CONFIRMED, at most 6 seats, fare non-negative.
--    (Replaces "with check (true)" from supabase-schema.sql.)
-- ------------------------------------------------------------
drop policy if exists "bookings_anon_insert" on public.bus_bookings;
create policy "bookings_anon_insert"
  on public.bus_bookings for insert
  to anon, authenticated
  with check (
    status = 'CONFIRMED'
    and jsonb_typeof(seats) = 'array'
    and jsonb_array_length(seats) between 1 and 6
    and total_fare >= 0
    and cancelled_at is null
    and refund_amount is null
  );

-- ------------------------------------------------------------
-- 6. SERVER-SIDE CANCELLATION (refund computed from the server clock + stored fare)
--    The browser must never decide the refund amount. This RPC re-reads the row,
--    recomputes the tier server-side, and writes status/cancelled_at/refund_amount
--    atomically. RLS still applies: the caller must own the booking (or be admin).
-- ------------------------------------------------------------
create or replace function public.cancel_booking(p_pnr text)
returns public.bus_bookings
language plpgsql
security definer
set search_path = public
as $$
declare
  b public.bus_bookings;
  hrs numeric;
  pct int;
  refund numeric;
begin
  select * into b from public.bus_bookings where pnr = p_pnr;
  if not found then raise exception 'Booking not found'; end if;

  -- ownership check (mirrors the RLS owner/admin rule)
  if not (
    lower(b.contact_email) = lower(coalesce(auth.jwt() ->> 'email','')) or public.is_admin()
  ) then
    raise exception 'Not authorised to cancel this booking';
  end if;

  if b.status <> 'CONFIRMED' then raise exception 'Booking is not active'; end if;

  -- date + time => timestamp; cast to timestamptz (session tz) before comparing to now()
  hrs := extract(epoch from (
           (b.journey_date + coalesce(nullif(b.departure_time,''),'00:00')::time)::timestamptz - now()
         )) / 3600.0;

  pct := case
           when hrs >= 24 then 90
           when hrs >= 12 then 70
           when hrs >= 4  then 50
           else 0
         end;
  refund := round(b.total_fare * pct / 100.0);

  update public.bus_bookings
     set status = 'CANCELLED', cancelled_at = now(), refund_amount = refund
   where pnr = p_pnr and status = 'CONFIRMED'
   returning * into b;

  return b;
end;
$$;

grant execute on function public.cancel_booking(text) to authenticated;

-- ------------------------------------------------------------
-- 7. (Optional) prevent direct client UPDATEs to money/status columns.
--    Once the app calls cancel_booking() above, you can drop the broad owner
--    UPDATE policy so refund_amount/total_fare/status can't be PATCHed directly:
--
--    drop policy if exists "bookings_owner_update" on public.bus_bookings;
--
--    (Leave it in place until app.js confirmCancel is switched to the RPC.)
-- ============================================================
