-- ============================================================
--  MS TRAVELS — VRL-STYLE BUS BOOKING — SUPABASE SCHEMA
--  Run this whole file in:  Supabase Dashboard → SQL Editor → New query
--  Project: saywqwlgamcltgbsmudk
-- ============================================================

-- ------------------------------------------------------------
-- 1. ROUTES / SCHEDULES TABLE
-- ------------------------------------------------------------
create table if not exists public.bus_routes (
  id               bigint generated by default as identity primary key,
  operator         text    not null,                 -- e.g. 'MS Travels'
  bus_type         text    not null,                 -- e.g. 'A/C Sleeper (2+1)'
  source_city      text    not null,
  destination_city text    not null,
  departure_time   text    not null,                 -- 'HH:MM' 24h
  arrival_time     text    not null,                 -- 'HH:MM' 24h
  duration         text    not null,                 -- '08h 30m'
  fare             numeric not null,
  total_seats      int     not null default 30,
  rating           numeric not null default 4.2,
  amenities        jsonb   not null default '[]'::jsonb,   -- ["Charging Point","Water Bottle"]
  boarding_points  jsonb   not null default '[]'::jsonb,   -- [{"name":"Majestic","time":"21:30"}]
  dropping_points  jsonb   not null default '[]'::jsonb,
  is_active        boolean not null default true,
  created_at       timestamptz not null default now()
);

-- ------------------------------------------------------------
-- 2. BOOKINGS TABLE
-- ------------------------------------------------------------
create table if not exists public.bus_bookings (
  id              bigint generated by default as identity primary key,
  pnr             text    not null unique,
  route_id        bigint  not null references public.bus_routes(id),
  journey_date    date    not null,
  source_city     text    not null,
  destination_city text   not null,
  operator        text    not null,
  bus_type        text    not null,
  departure_time  text    not null,
  arrival_time    text    not null,
  seats           jsonb   not null,                  -- ["L1","L2"]
  passengers      jsonb   not null,                  -- [{"seat":"L1","name":"..","age":30,"gender":"M"}]
  boarding_point  jsonb   not null,                  -- {"name":"Majestic","time":"21:30"}
  dropping_point  jsonb   not null,
  contact_name    text    not null,
  contact_email   text    not null,
  contact_phone   text    not null,
  total_fare      numeric not null,
  status          text    not null default 'CONFIRMED',
  created_at      timestamptz not null default now()
);

-- Fast seat-availability lookups (which seats are booked for a route on a date)
create index if not exists idx_bookings_route_date
  on public.bus_bookings (route_id, journey_date);

-- ------------------------------------------------------------
-- 3. ROW LEVEL SECURITY
--    Frontend uses the public anon key, so we allow:
--      - anyone to READ active routes
--      - anyone to READ + CREATE bookings (demo app, no auth)
-- ------------------------------------------------------------
alter table public.bus_routes   enable row level security;
alter table public.bus_bookings enable row level security;

drop policy if exists "routes_public_read" on public.bus_routes;
create policy "routes_public_read"
  on public.bus_routes for select
  using (true);

drop policy if exists "bookings_public_read" on public.bus_bookings;
create policy "bookings_public_read"
  on public.bus_bookings for select
  using (true);

drop policy if exists "bookings_public_insert" on public.bus_bookings;
create policy "bookings_public_insert"
  on public.bus_bookings for insert
  with check (true);

-- ============================================================
-- 4. SEED DATA — VRL-style routes
-- ============================================================
insert into public.bus_routes
  (operator, bus_type, source_city, destination_city, departure_time, arrival_time, duration, fare, total_seats, rating, amenities, boarding_points, dropping_points)
values
  -- operator changed from VRL Travels → MS Travels
  ('MS Travels', 'A/C Sleeper (2+1)',     'Bangalore', 'Hyderabad', '21:00', '06:30', '09h 30m', 1299, 30, 4.5,
   '["Charging Point","Water Bottle","Blanket","Reading Light","CCTV"]'::jsonb,
   '[{"name":"Majestic Bus Stand","time":"21:00"},{"name":"Kalasipalya","time":"21:20"},{"name":"Yeshwantpur","time":"21:45"}]'::jsonb,
   '[{"name":"MGBS","time":"06:00"},{"name":"Miyapur","time":"06:30"},{"name":"Ameerpet","time":"06:45"}]'::jsonb),

  ('MS Travels', 'Non A/C Sleeper (2+1)', 'Bangalore', 'Hyderabad', '22:30', '07:30', '09h 00m', 999, 30, 4.2,
   '["Charging Point","Water Bottle","Reading Light"]'::jsonb,
   '[{"name":"Majestic Bus Stand","time":"22:30"},{"name":"Hebbal","time":"23:00"}]'::jsonb,
   '[{"name":"MGBS","time":"07:00"},{"name":"Kukatpally","time":"07:30"}]'::jsonb),

  ('MS Travels', 'A/C Seater / Sleeper (2+1)', 'Mumbai', 'Pune', '06:00', '09:30', '03h 30m', 549, 36, 4.3,
   '["Charging Point","Water Bottle","WiFi","Reading Light"]'::jsonb,
   '[{"name":"Dadar","time":"06:00"},{"name":"Sion","time":"06:20"},{"name":"Vashi","time":"06:50"}]'::jsonb,
   '[{"name":"Wakad","time":"09:00"},{"name":"Shivaji Nagar","time":"09:30"}]'::jsonb),

  ('MS Travels', 'A/C Sleeper (2+1)',     'Bangalore', 'Goa',       '20:00', '07:00', '11h 00m', 1499, 30, 4.6,
   '["Charging Point","Water Bottle","Blanket","Reading Light","Emergency Exit","CCTV"]'::jsonb,
   '[{"name":"Majestic Bus Stand","time":"20:00"},{"name":"Yeshwantpur","time":"20:30"}]'::jsonb,
   '[{"name":"Mapusa","time":"06:30"},{"name":"Panaji","time":"07:00"}]'::jsonb),

  ('MS Travels', 'A/C Sleeper (2+1)',     'Hyderabad', 'Bangalore', '21:30', '07:00', '09h 30m', 1349, 30, 4.4,
   '["Charging Point","Water Bottle","Blanket","Reading Light","CCTV"]'::jsonb,
   '[{"name":"MGBS","time":"21:30"},{"name":"Ameerpet","time":"21:50"},{"name":"Miyapur","time":"22:10"}]'::jsonb,
   '[{"name":"Yeshwantpur","time":"06:30"},{"name":"Majestic Bus Stand","time":"07:00"}]'::jsonb),

  ('MS Travels', 'A/C Seater (2+2)',      'Pune',      'Mumbai',    '18:00', '21:15', '03h 15m', 499, 40, 4.1,
   '["Charging Point","WiFi","Reading Light"]'::jsonb,
   '[{"name":"Shivaji Nagar","time":"18:00"},{"name":"Wakad","time":"18:30"}]'::jsonb,
   '[{"name":"Vashi","time":"20:45"},{"name":"Dadar","time":"21:15"}]'::jsonb),

  ('MS Travels', 'A/C Sleeper (2+1)',     'Bangalore', 'Chennai',   '23:00', '05:00', '06h 00m', 899, 30, 4.0,
   '["Charging Point","Water Bottle","Blanket","CCTV"]'::jsonb,
   '[{"name":"Madiwala","time":"23:00"},{"name":"Electronic City","time":"23:30"}]'::jsonb,
   '[{"name":"Koyambedu","time":"04:30"},{"name":"CMBT","time":"05:00"}]'::jsonb),

  ('MS Travels', 'Non A/C Sleeper (2+1)', 'Goa',       'Bangalore', '19:30', '06:30', '11h 00m', 1199, 30, 4.2,
   '["Charging Point","Water Bottle","Reading Light"]'::jsonb,
   '[{"name":"Panaji","time":"19:30"},{"name":"Mapusa","time":"20:00"}]'::jsonb,
   '[{"name":"Yeshwantpur","time":"06:00"},{"name":"Majestic Bus Stand","time":"06:30"}]'::jsonb);
